permalink: /:year/:month/:day/:title.html

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]
# Build settings
markdown: kramdown
highlighter: pygments

sass:
  sass_dir: public/css
  style: :compressed